import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';
import { Toaster } from "react-hot-toast"; // Import Toaster
import { AuthProvider } from '@/contexts/AuthContext';
import Navbar from '../components/Navbar';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kishan2Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="bg-gray-100 ">
          {/* Navigation Bar */}
          <Navbar />

          {/* Main Content */}
          <main className="w-full mx-auto pt-10 sm:px-0 lg:px-0 overflow-y-hidden">
          {/* <main className=""> */}
            {children}
          </main>
        </div>

          {/* Toaster for notifications */}
          <Toaster position="top-right" reverseOrder={false} /> {/* Toaster placed here */}
        </AuthProvider>
      </body>
    </html>
  );
}
